// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAam_-_qntU7Bz20UhA6BDZoeWv-e4cn1o',
    appId: '1:654895990962:web:cb9f7bd2c4fd6cdbc9a1ab',
    messagingSenderId: '654895990962',
    projectId: 'cuboplayer-44081',
    authDomain: 'cuboplayer-44081.firebaseapp.com',
    storageBucket: 'cuboplayer-44081.firebasestorage.app',
    measurementId: 'G-ZVCT2920S9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXeqABfvJBNMODWAQ8UKRVR0zFSUH0o2w',
    appId: '1:654895990962:android:b182f35a4d426367c9a1ab',
    messagingSenderId: '654895990962',
    projectId: 'cuboplayer-44081',
    storageBucket: 'cuboplayer-44081.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2eoa8IxWwObe_0CSXAICJKjk2RbUMM0o',
    appId: '1:654895990962:ios:72cc671d0e4374d5c9a1ab',
    messagingSenderId: '654895990962',
    projectId: 'cuboplayer-44081',
    storageBucket: 'cuboplayer-44081.firebasestorage.app',
    iosBundleId: 'com.example.playerApp',
  );
}
